name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  ecommerce_analytics:
    # Configure models by directory
    staging:
      +materialized: view
      +schema: staging
    
    intermediate:
      +materialized: table
      +schema: intermediate
    
    marts:
      +materialized: table
      +schema: marts
      +tags: ["reporting"]