version: 2

sources:
  - name : ga4
    database: bigquery-public-data
    schema : ga4_obfuscated_sample_ecommerce
    tables:
      - name: events*
        identifier: events_{{var('date_range','20210101')}}
